### ISSUE TITLE
Org transfer?

### ISSUE THREAD

**Issue by clmay** [BranchTaken/Hemlock#98]
Hey all,

I'm a student of programming language theory and implementation and had planned to name my project Hemlock as well. In anticipation of this, I reserved the org at https://github.com/hemlock-lang. I was thinking something a little more Elm/Haskell-ish but still wanted to pay homage to the ML lineage via the name (He***ml***ock) and file extension (I'd planned to use `.hml` instead).

Since then, I've been derailed by work changes and the pandemic, and never quite got round to starting.

Since you've already made pretty good headway with your project (the name really is too good to pass up, isn't it?), would you like me to transfer the organization ownership to you?

**Comment by jasone** [comment]
Hi @cl

**Comment by jasone** [comment]
Hi @clmay, thanks for bringing this up! It's hard to come up with a good unused name, eh? It's a bit surprising that the name hadn't been used in earnest before we both thought of it, but on the other hand, an awful lot of the other ideas I came up with before Hemlock *are* taken.

I'm currently content with using `BranchTaken/Hemlock`, and I made the repo public before Hemlock is really ready for use in part so that others could discover that the name is in use for an active project. Search engine results are hit-and-miss, though it's pretty easy to find when searching GitHub directly. I could imagine someday moving the master repo over to the `hemlock-lang` org, but we're still at least a couple years from having a self-hosting compiler... I'd be happy to take over the `hemlock-lang` org, but for the time being I would just direct people who discover it to look here. Totally up to you whether you consider that worthy use to justify transfer.

**Comment by clmay** [comment]
Yes, it really is hard to find a good name, especially a pretty good one like Hemlock! You're right that web search results are pretty mixed at the moment, but luckily almost all existing results are in unrelated disciplines; once the project gains traction, I'm sure you'll do alright. If Go could overcome the name-searchability problem as well as it has (remember when we all had to search "golang" instead?), anything is possible for a name like Hemlock.

Anyway, down to business, if you're comfortable with the transfer, let's just go ahead with it? Then you can decide how/if you want to use it / delete it at any point down the road as it suits you.

The transfer itself is easy; I've added you as an org owner per the [GH docs](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/transferring-organization-ownership), have a look and let me know if you can manage the settings? It's currently at the free tier, and I never entered any billing info, so that portion shouldn't be an issue.

**Comment by jasone** [comment]
All done. Thanks!
